### ISSUE TITLE
vagrant box not working for serve or run

### ISSUE THREAD

**Issue by guyjacks** [driftyco/ionic-box#31]
I've tried ionic serve and run.

ionic run: 
This is the output: http://pastebin.com/jWigsKVw

I've Googled this 30 different ways and still cannot figure out why it won't work.  It may have nothing to do with Ionic though.  I'm not even sure my Mac is detecting my phone.  I tried installing a driver for it (Motorola Razr M) and that did nothing.

ionic serve: 

css/ionic.app.css - this link is broken

I think its because vagrant fails to install sass and many other dependencies.  As a result the scss files are not compiled.

I manually installed and compiled the scss and got this to work.  However, things still didn't look right.

Even if that css file was there, many other resources cannot be found because ionic hardcodes the port number for files...

Example: document.write('<script src="' + (location.protocol || 'http:') + '//' + (location.hostname || 'localhost') + ':35729/livereload.js?snipver=1" 

This breaks the app on the host OS.  I could not figure out where override this.

Finally, the font icons are nowhere to be found.  There isn't even a fonts folder as far as I can tell.

**Comment by davidkassa** [comment]
I cannot perform an ionic run (yet) but it looks like there might be a workaround here: https://github.com/driftyco/ionic-box/issues/22

ionic serve works for me but you need to turn on port forwarding for 8100 and 35729 in you virtualbox. This should probably be added to the vagrant definition (assuming they're well-defined ports).

Ahh, now reading I see you had the sass problem you referenced in issue #30. I've added the workaround there but you just need to install gulp.

**Comment by Ionitron** [comment]
Greetings @guyjacks!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
