### ISSUE TITLE
up and running with ionic-box

### ISSUE THREAD

**Issue by moeinrahimi** [driftyco/ionic-box#59]
hi
I just downloaded ionic-box and download dependencies via vagrant, now i can run vagrant ssh and it works prefect but I don't know what to do next, how to create new ionic app ?

**Comment by csukcc** [comment]
I don't think this repo is meant to contain instructions on how to create ionic app, you might find their official site more useful: http://ionicframework.com/getting-started/

**Comment by moeinrahimi** [comment]
ok...well it was sort of a simple question cause i didn't know about vagrant and what is it's usage.
